FROM node:22-alpine

WORKDIR /npm_cache
COPY ./package*.json ./
RUN npm install

WORKDIR /app

ENTRYPOINT [ "/bin/sh", "-c", "cp -r /npm_cache/node_modules/. /app/node_modules && exec \"$0\" \"$@\"" ]

CMD ["npm", "run", "dev"]