FROM node:22-alpine

# install nginx
RUN apk add nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY ./ .

ENTRYPOINT [ "/bin/sh", "-c" ]

CMD ["npm run build && nginx -g 'daemon off;'"]
